### ISSUE TITLE
a problem about install

### ISSUE THREAD

**Issue by Lumos1110** [mark-hobbs/PyPD#14]
ERROR: Could not find a version that satisfies the requirement pkgutil (from versions: none)
ERROR: No matching distribution found for pkgutil

**Comment by mark-hobbs** [comment]
This issue is related to your local machine rather than `PyPD`. `pkgutil` is part of the standard library, offering utilities for finding and working with Python packages.  

To observe `PyPD` in action, I suggest you open and run the following notebook in Google Colab.

<a href="https://colab.research.google.com/github/mark-hobbs/PyPD/blob/main/examples/crack_branching.ipynb" target="_parent">
<img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

**Comment by Lumos1110** [comment]
yeah，the problem has been soluted！Also I have the following questions:
1, I found a three point bending model in your example file. When I simulate with matlab, the load displacement application is usually done on the internal dx layer particles. But the load in the three point bend is applied on the particles located on L/2, so I don't understand how to apply it, is it easy for you to guide me?
2, PeriPY is based on BBPD, so if I want to use SBPD, how can I modify it?

**Comment by mark-hobbs** [comment]
Your questions are unrelated to the original issue so I'm going to close this issue, but I will briefly respond.

1. Clearly, it is up to you how you decide to apply the load, but ask yourself if it is physically realistic to apply the load to internal particles? The three point bending example (`examples/half_notched_beam.py`) uses a contact model, and loads are not directly applied to particles.
2. `PeriPy` is a different package. But yes it would be possible to modify for state-based simulations. Obviously this is something that you will have to figure out yourself. 

For more general questions about peridynamics, feel free to email me, and I will be more than happy to help.
